name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake configure
      run: mkdir ../test_build;pwd;ls -lah; cd ../test_build; cmake ../foundry_take_home_test
    - name: cmake build
      run: cd /home/runner/work/foundry_take_home_test/test_build; cmake --build
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
